version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=compound_backend_user
      - POSTGRES_PASSWORD=compound_backend_pwd
      - POSTGRES_DB=compound_backend
  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - COMPOUND_BACKEND_DB_PWD=compound_backend_pwd
      - COMPOUND_BACKEND_DB_HOST=db
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app/
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data:
