# Generated by Django 3.2.11 on 2022-01-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('compound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('smiles', models.CharField(max_length=200)),
                ('molecular_weight', models.FloatField()),
                ('ALogP', models.FloatField()),
                ('molecular_formula', models.CharField(max_length=100)),
                ('num_rings', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssayResult',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=300)),
                ('result', models.CharField(choices=[('IC50', 'IC50'), ('KI', 'Ki'), ('KD', 'Kd')], max_length=30)),
                ('operator', models.CharField(choices=[('EQ', '='), ('GT', '>'), ('GE', '>='), ('LT', '<'), ('LE', '<='), ('AE', '~'), ('*', '*')], max_length=2)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
            ],
        ),
    ]
